version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true